### PR TITLE
Fix error due to new use of coerce method

### LINKED ISSUE #9: Failing specs due to the new use of Ruby coerce method
Problem was introduced with this modification on equalizer gem:
- https://github.com/dkubb/equalizer/commit/0f13

Failing specs:
```
$ rspec

Randomized with seed 31093
FF........F..F...

Failures:

  1) DummyPost should have body defined
     Failure/Error: it { expect(described_class).to have_attribute(:body).of_type(String) }
     NoMethodError:
       undefined method `first' for nil:NilClass
     # /home/embs/.rvm/gems/ruby-2.1.2@rspec-virtus/gems/equalizer-0.0.11/lib/equalizer.rb:117:in `=='
     # ./lib/rspec-virtus/matcher.rb:47:in `!='
     # ./lib/rspec-virtus/matcher.rb:47:in `attribute_exists?'
     # ./lib/rspec-virtus/matcher.rb:21:in `matches?'
     # ./spec/acceptance/rspec-virtus_spec.rb:14:in `block (2 levels) in <top (required)>'

  2) DummyPost should have title defined
     Failure/Error: it { expect(described_class).to have_attribute(:title) }
     NoMethodError:
       undefined method `first' for nil:NilClass
     # /home/embs/.rvm/gems/ruby-2.1.2@rspec-virtus/gems/equalizer-0.0.11/lib/equalizer.rb:117:in `=='
     # ./lib/rspec-virtus/matcher.rb:47:in `!='
     # ./lib/rspec-virtus/matcher.rb:47:in `attribute_exists?'
     # ./lib/rspec-virtus/matcher.rb:21:in `matches?'
     # ./spec/acceptance/rspec-virtus_spec.rb:13:in `block (2 levels) in <top (required)>'

  3) RSpec::Virtus::Matcher#matches? successful match on attribute name 
     Failure/Error: subject { instance.matches?(actual) }
     NoMethodError:
       undefined method `first' for nil:NilClass
     # /home/embs/.rvm/gems/ruby-2.1.2@rspec-virtus/gems/equalizer-0.0.11/lib/equalizer.rb:117:in `=='
     # ./lib/rspec-virtus/matcher.rb:47:in `!='
     # ./lib/rspec-virtus/matcher.rb:47:in `attribute_exists?'
     # ./lib/rspec-virtus/matcher.rb:21:in `matches?'
     # ./spec/lib/rspec-virtus/matcher_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/lib/rspec-virtus/matcher_spec.rb:20:in `block (4 levels) in <top (required)>'

  4) RSpec::Virtus::Matcher#matches? successful match on attribute name and type 
     Failure/Error: subject { instance.matches?(actual) }
     NoMethodError:
       undefined method `first' for nil:NilClass
     # /home/embs/.rvm/gems/ruby-2.1.2@rspec-virtus/gems/equalizer-0.0.11/lib/equalizer.rb:117:in `=='
     # ./lib/rspec-virtus/matcher.rb:47:in `!='
     # ./lib/rspec-virtus/matcher.rb:47:in `attribute_exists?'
     # ./lib/rspec-virtus/matcher.rb:21:in `matches?'
     # ./spec/lib/rspec-virtus/matcher_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/lib/rspec-virtus/matcher_spec.rb:28:in `block (4 levels) in <top (required)>'

Finished in 0.00842 seconds (files took 0.13039 seconds to load)
17 examples, 4 failures

Failed examples:

rspec ./spec/acceptance/rspec-virtus_spec.rb:14 # DummyPost should have body defined
rspec ./spec/acceptance/rspec-virtus_spec.rb:13 # DummyPost should have title defined
rspec ./spec/lib/rspec-virtus/matcher_spec.rb:20 # RSpec::Virtus::Matcher#matches? successful match on attribute name 
rspec ./spec/lib/rspec-virtus/matcher_spec.rb:28 # RSpec::Virtus::Matcher#matches? successful match on attribute name and type
```

### PR DESCRIPTION
**Pull request by embs**
This commit fixes failing specs. Closes #9

Failures were introduced by the new use of Ruby coerce method in
equalizer gem, according to the following commit:
- https://github.com/dkubb/equalizer/commit/0f13

### CODE REVIEW

File: lib/rspec-virtus/matcher.rb [hunk 1]
```diff
@@ -44,7 +44,7 @@ def attribute_type
       end
 
       def attribute_exists?
-        attribute != nil
+        not attribute.nil?
```
Comment (mikespokefire) [inline lib/rspec-virtus/matcher.rb]: Could you change this to `!attribute.nil?` please? I've never really been a fan of Ruby's not keyword.

Will merge and release a release a new version once this is done :+1:

Comment (embs) [inline lib/rspec-virtus/matcher.rb]: Done!

**Comment by mikespokefire** [comment]
Released `v1.0.2` for you. Thanks for doing this :+1:

**Comment by embs** [comment]
Thanks, @mikespokefire. :smile:
